# Generated by Django 4.1 on 2022-09-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_profile', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('user', models.CharField(max_length=15)),
                ('createdAT', models.DateField()),
                ('updateAT', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(default='Admin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.IntegerField(primary_key=True, serialize=False)),
                ('concept', models.CharField(max_length=80)),
                ('amount', models.FloatField(max_length=10)),
                ('enterprises', models.CharField(max_length=30)),
                ('createdAT', models.DateField()),
                ('updateAT', models.DateField()),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id_enterprise', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=20)),
                ('createdAT', models.DateField()),
                ('updateAT', models.DateField()),
                ('id_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.profile')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employe', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('createdAT', models.DateField()),
                ('updateAT', models.DateField()),
                ('id_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.enterprise')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.rol')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.transaction')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiCiclo3.profile')),
            ],
        ),
    ]
